### ISSUE TITLE
要件（8月12日）

### ISSUE THREAD

**Issue by cawahara** [Shantti-Y/Noh-event#5]
追加要件
・検索項目の順番は日付、エリア、キーワード
・演目舞台の周辺情報を非表示にする（初期機能から外したため）
・「主催者」ではなく「登録者」、という表記にする（主催者でなくても登録できるため）

**Comment by Shantti-Y** [comment]
Fixed
664174bb6832a8fdd426a3d570c48a3ac2e0c366

**Comment by Shantti-Y** [comment]
Fixed
664174bb6832a8fdd426a3d570c48a3ac2e0c366
